version: "3.9"
services:
  __container__-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5000/__container__-debug:${TAG}
    ports:
      - 2222:2222
      - 9229:9229
